-- Create course_resources table
CREATE TABLE IF NOT EXISTS course_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('video', 'tool')),
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_course_resources_course_id ON course_resources(course_id);

-- RLS Policies (if RLS is enabled, but we generally use service role for admin, public read for users often handled via app logic, but good to have)
ALTER TABLE course_resources ENABLE ROW LEVEL SECURITY;

-- Allow public read access (for course reader)
CREATE POLICY "Public read access" ON course_resources FOR SELECT USING (true);

-- Allow admin full access (usually handled by service role key in our app, but for completeness)
-- Note: Our app uses supabaseAdmin for admin ops, so RLS doesn't block it.

-- Optional: Drop old columns if you want to clean up immediately
-- ALTER TABLE courses DROP COLUMN IF EXISTS video_link_1;
-- ALTER TABLE courses DROP COLUMN IF EXISTS video_link_2;
